const jwt = require("jsonwebtoken")

// Return the token generated by jwt.verify().

const generateToken = (userId, recoverPassword) => {
  // If the user is trying to recover his password,
  // he'll have 1 hour to do so. Otherwise, the token
  // will be set to expire within 2 days.

  const token = jwt.sign(
    { userId }, // token identification
    process.env.JWT_SECRET, // secret phrase
    { expiresIn: recoverPassword ? "1 hour" : "2 days" } // options
  )

  return token
}

module.exports = generateToken
